"use client";

import Image from "next/image";
import Link from "next/link";
import { useCart } from "@/components/cart-provider";

export function CartView() {
  const { items, subtotal, updateQuantity, removeItem } = useCart();
  if (!items.length) return <section className="mx-auto max-w-3xl px-5 py-20 text-center"><p className="text-[10px] font-bold tracking-[0.18em] text-[var(--accent)] uppercase">Your bag</p><h1 className="mt-3 font-[family-name:var(--font-cormorant)] text-6xl tracking-[-0.05em]">Nothing here yet.</h1><p className="mt-5 text-[var(--ink-muted)]">Start with a piece that carries its own material and making story.</p><Link href="/shop" className="mt-8 inline-flex rounded-full bg-[var(--foreground)] px-6 py-3 text-xs font-bold tracking-[0.14em] text-white uppercase">Browse the collection</Link></section>;
  return <section className="mx-auto grid max-w-7xl gap-10 px-5 py-12 sm:px-8 lg:grid-cols-[1fr_360px] lg:px-12"><div><p className="text-[10px] font-bold tracking-[0.18em] text-[var(--accent)] uppercase">Your bag</p><h1 className="mt-3 font-[family-name:var(--font-cormorant)] text-6xl tracking-[-0.05em]">Pieces selected.</h1><div className="mt-10 divide-y divide-[var(--line)] border-y border-[var(--line)]">{items.map((item) => <article key={item.lineId} className="grid grid-cols-[96px_1fr] gap-4 py-5 sm:grid-cols-[120px_1fr_auto]"><Image src={item.image} alt="" width={160} height={200} unoptimized className="aspect-[4/5] h-full w-full object-cover" /><div><Link href={`/shop/${item.productSlug}`} className="font-[family-name:var(--font-cormorant)] text-3xl leading-none hover:text-[var(--accent)]">{item.title}</Link><p className="mt-2 text-sm text-[var(--ink-muted)]">{item.variantTitle}</p>{item.customisationNote && <p className="mt-2 text-xs leading-5 text-[var(--ink-muted)]">Maker note: {item.customisationNote}</p>}<div className="mt-4 flex items-center gap-3"><label className="text-xs font-bold tracking-[0.12em] uppercase">Qty <select aria-label={`Quantity for ${item.title}`} value={item.quantity} onChange={(event) => updateQuantity(item.lineId, Number(event.target.value))} className="ml-2 border border-[var(--line)] bg-white px-2 py-1">{Array.from({ length: 10 }, (_, index) => index + 1).map((quantity) => <option key={quantity}>{quantity}</option>)}</select></label><button type="button" onClick={() => removeItem(item.lineId)} className="text-xs font-semibold text-[var(--accent)] underline">Remove</button></div></div><p className="hidden font-medium sm:block">₹{(item.unitPrice * item.quantity).toLocaleString("en-IN")}</p></article>)}</div></div><aside className="h-fit rounded-2xl bg-[#203027] p-6 text-white"><p className="text-[10px] font-bold tracking-[0.16em] text-[#e1b495] uppercase">Order summary</p><div className="mt-7 flex justify-between text-sm text-[#d5ddd6]"><span>Subtotal</span><span>₹{subtotal.toLocaleString("en-IN")}</span></div><p className="mt-3 text-xs leading-5 text-[#b6c3b9]">Delivery, tax and eligible payment methods are confirmed at checkout using your validated address.</p><Link href="/checkout" className="mt-7 block rounded-full bg-[#e1b495] px-5 py-4 text-center text-xs font-bold tracking-[0.14em] text-[#203027] uppercase">Continue to checkout</Link></aside></section>;
}
