const modules = [
  ["Multi-currency display", "Ready", "Presentation-only formatting preserves the authoritative checkout/order currency until approved FX pricing is configured."],
  ["Wishlist", "Ready", "Authenticated, owner-scoped save/remove behaviour prevents duplicate saved product lines."],
  ["Reviews", "Moderation foundation", "Only an attributable delivered purchase can submit a pending review. No ratings or reviews are fabricated."],
  ["Production queue", "Ready", "Made-to-order jobs support queued, in-progress, quality review and ready-to-ship transitions."],
  ["Courier tracking", "Sandbox", "Idempotent carrier-event persistence exists; live courier credentials and signature verification remain required."],
  ["Marketing", "Sandbox", "Marketing requires explicit opt-in. Email/WhatsApp campaigns and abandoned-cart sending remain disabled."],
  ["Analytics", "Fail closed", "GA4, Meta Pixel and Search Console cannot activate without client-owned identifiers and consent-aware wiring."],
  ["Editorial SEO", "Foundation", "Article/lookbook and internal redirect models are ready for authorised publishing workflows."],
] as const;

export function GrowthModulesWorkspace() { return <main className="mx-auto max-w-6xl px-5 py-10 sm:px-8 lg:px-12"><p className="text-[10px] font-bold tracking-[0.18em] text-[var(--accent)] uppercase">Owner workspace · growth operations</p><h1 className="mt-3 font-[family-name:var(--font-cormorant)] text-6xl tracking-[-0.05em]">Advanced module status</h1><p className="mt-4 max-w-3xl text-sm leading-6 text-[var(--ink-muted)]">This workspace shows what is safe to enable in the shared Odhvica foundation. A status of “sandbox” or “fail closed” means no external provider call, marketing send, tracking pixel or courier action is active.</p><section className="mt-9 grid gap-4 md:grid-cols-2">{modules.map(([title, status, description]) => <article key={title} className="rounded-2xl border border-[var(--line)] bg-white p-6"><div className="flex items-start justify-between gap-4"><h2 className="font-[family-name:var(--font-cormorant)] text-3xl">{title}</h2><span className="rounded-full bg-[#f5f3ee] px-3 py-1 text-[10px] font-bold tracking-[0.13em] text-[var(--accent)] uppercase">{status}</span></div><p className="mt-4 text-sm leading-6 text-[var(--ink-muted)]">{description}</p></article>)}</section><section className="mt-8 rounded-2xl bg-[#f5f3ee] p-6 text-sm leading-6 text-[var(--ink-muted)]"><strong className="text-[var(--foreground)]">Live activation rule:</strong> enable only one client-owned provider/module at a time after its credentials, consent/legal requirements, failure handling, observability and test procedure are approved. Never copy keys or account identifiers into source code.</section></main>; }
