import type { EmailMode } from "@/lib/notifications/config";

const eventGroups = [
  ["Order confirmed", "Transactional", "Always eligible"],
  ["Payment failed", "Transactional", "Always eligible"],
  ["Fulfilment update", "Transactional", "Always eligible"],
  ["Refund approved", "Transactional", "Always eligible"],
  ["Staff alert", "Operational", "Preference controlled"],
] as const;

export function NotificationSandboxWorkspace({ mode }: { mode: EmailMode }) {
  return <main className="mx-auto max-w-6xl px-5 py-10 sm:px-8 lg:px-12"><p className="text-[10px] font-bold tracking-[0.18em] text-[var(--accent)] uppercase">Staff workspace · notification delivery</p><h1 className="mt-3 font-[family-name:var(--font-cormorant)] text-6xl tracking-[-0.05em]">Email sandbox status</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-[var(--ink-muted)]">The notification engine is currently in {mode} mode. It records test delivery attempts with masked recipients only. No real email, provider API call, secret or full message body is available here.</p><section className="mt-10 grid gap-4 md:grid-cols-3"><article className="rounded-2xl border border-[var(--line)] bg-white p-6"><p className="text-[10px] font-bold tracking-[0.14em] text-[var(--accent)] uppercase">Delivery mode</p><p className="mt-4 font-[family-name:var(--font-cormorant)] text-4xl capitalize">{mode}</p><p className="mt-2 text-sm leading-6 text-[var(--ink-muted)]">No-network email adapter. Live sending remains disabled.</p></article><article className="rounded-2xl border border-[var(--line)] bg-white p-6"><p className="text-[10px] font-bold tracking-[0.14em] text-[var(--accent)] uppercase">Recipient privacy</p><p className="mt-4 font-[family-name:var(--font-cormorant)] text-4xl">Masked</p><p className="mt-2 text-sm leading-6 text-[var(--ink-muted)]">Staff status views show addresses such as c•••••••@example.com only.</p></article><article className="rounded-2xl border border-[var(--line)] bg-white p-6"><p className="text-[10px] font-bold tracking-[0.14em] text-[var(--accent)] uppercase">Delivery history</p><p className="mt-4 font-[family-name:var(--font-cormorant)] text-4xl">Pending DB</p><p className="mt-2 text-sm leading-6 text-[var(--ink-muted)]">Attempts populate after the production PostgreSQL migration is applied.</p></article></section><section className="mt-8 overflow-hidden rounded-2xl border border-[var(--line)] bg-white"><div className="grid grid-cols-[1.3fr_0.9fr_1fr] gap-4 border-b border-[var(--line)] bg-[#f5f3ee] px-5 py-3 text-[10px] font-bold tracking-[0.14em] text-[var(--ink-muted)] uppercase"><span>Event</span><span>Class</span><span>Delivery rule</span></div>{eventGroups.map(([event, deliveryClass, rule]) => <div key={event} className="grid grid-cols-[1.3fr_0.9fr_1fr] gap-4 px-5 py-4 text-sm"><span className="font-semibold">{event}</span><span>{deliveryClass}</span><span className="text-[var(--ink-muted)]">{rule}</span></div>)}</section><section className="mt-8 rounded-2xl bg-[#f5f3ee] p-6 text-sm leading-6 text-[var(--ink-muted)]"><strong className="text-[var(--foreground)]">Live activation checklist:</strong> configure a client-owned sender domain, add the live email provider key securely, verify DNS records, set sender name/address, test a real opt-in inbox, and only then enable live mode. No secret should be copied into source code or this workspace.</section></main>;
}
